// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/26/2024, 10:04:54 AM
const configMerger = require("/Users/weha/Documents/Project/slowboat/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/weha/Documents/Project/slowboat/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/plugins/**/*.{js,ts,mjs}","/Users/weha/Documents/Project/slowboat/composables/**/*.{js,ts,mjs}","/Users/weha/Documents/Project/slowboat/utils/**/*.{js,ts,mjs}","/Users/weha/Documents/Project/slowboat/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/weha/Documents/Project/slowboat/app.config.{js,ts,mjs}"] }));

module.exports = config
